### ISSUE TITLE
deployuVirtualMachine

### ISSUE THREAD

**Issue by BwOrK** [PCextreme/cloudstack-php#1] opened 2017-09-06 14:56 UTC
when I am trying to deploy a VM via API call I am not able to correctl transfer array which is containing the 
networks id to a variable  "iptonetworklist"

can you tell me how to do it,

$cloudQuery = $this->cloudConnect->clientEurope()->command(......)
 
let me know
Thansk

**Comment by kevindierkx** [comment] 2017-12-11 12:57
@BwOrK If I'm not mistaken you only get a jobId from the deployVirtualMachine command. You can use this to query the async job result (`queryAsyncjobresult`). When the job succeeds there should be a nics array in the virtual machine response.

**Comment by kevindierkx** [comment] 2018-01-18 12:21
Closing this issue, can't reproduce the issue.

**Closed as completed by kevindierkx** 2018-01-18 12:21 UTC
